DavidWidjaja-dev
UBC-Solar/Firmware-v2 pull request #8
Opened 2019-06-08 23:44 UTC by DavidWidjaja-137

Speed Controller node

2019-06-09 10:21 UTC, cng123 requested changes

2019-06-09 10:21 UTC, cng123 commented on Speed_Controller/src/Encoder/encoder.c
> +
Should we move the filter code here?

2019-06-09 10:21 UTC, cng123 commented on Speed_Controller/src/Timer/Timer.c
> +
extra space

2019-06-09 10:21 UTC, cng123 commented on Speed_Controller/src/Timer/Timer.c
> +
spacing

2019-06-09 10:21 UTC, cng123 commented on Speed_Controller/src/Timer/Timer.h
> +/** Interrupt handler for Timer 2.
formatting

2019-06-09 10:21 UTC, cng123 commented on Speed_Controller/src/Timer/Timer.h
> +/** Initializes a timer to trigger a timing interrupt periodically
formatting

2019-06-09 10:21 UTC, cng123 commented on Speed_Controller/src/Timer/Timer.h
> +
should probably have header guards for this file

2019-06-09 10:21 UTC, cng123 commented on Speed_Controller/src/main.c
> +} u;
we should probably use better names

2019-06-09 10:21 UTC, cng123 commented on Speed_Controller/src/main.c
> +} v;
same as above

2019-06-09 10:21 UTC, cng123 commented on Speed_Controller/src/main.c
> +	RCC->APB2ENR |= 0x1 << 4;
should this be in its own module?

2019-06-09 10:21 UTC, cng123 commented on Speed_Controller/src/main.c
> +
spacing

2019-06-09 10:21 UTC, cng123 commented on Speed_Controller/src/main.c
> +
spacing

2019-06-09 10:21 UTC, cng123 commented on Speed_Controller/src/main.c
> +			if (u.float_var > 1.0 || u.float_var < 0.0)
should this be moved to the encoderRead function?

2019-06-09 10:21 UTC, cng123 commented on Speed_Controller/src/main.c
> +			old_ADC_reading = ADC_reading;
why is this in each branch? why can't they just be outside the cases and at the end of the while loop?

2019-06-09 10:21 UTC, cng123 commented on Peripherals/CAN/CAN.c
> +	CAN1->BTR |=  (((2-1) & 0x07) << 20) | (((15-1) & 0x0F) << 16) | ((2-1) & 0x1FF);
we should probably do something about this and add support to be able to change this via defining a constant

2019-06-09 10:21 UTC, cng123 commented on Speed_Controller/src/ADC/ADC.c
> +	// TODO: check sample time to see diff
we can remove this, don't remember there was a difference

2019-06-09 10:21 UTC, cng123 commented on Speed_Controller/src/ADC/ADC.c
> +	// TODO: check sample time to see diff
remove the comment, not the code

2019-06-09 10:21 UTC, cng123 commented on Speed_Controller/src/Timer/Timer.c
> +								//Clock frequency of 10kHz
spacing

2019-06-09 10:21 UTC, cng123 commented on Speed_Controller/src/Timer/Timer.h
> + * @param period: period for triggering the timing interrupt
units?

2019-06-09 10:21 UTC, cng123 commented on Speed_Controller/src/main.c
> +	TimerInit(100);
we should probably try increasing the period until the motor controller stops operating smoothly

2019-06-15 08:05 UTC, DavidWidjaja-137 commented on Speed_Controller/src/Encoder/encoder.c
> +
yea probably

2019-06-15 08:12 UTC, DavidWidjaja-137 commented
changes made to speed controller

2019-06-15 08:13 UTC, closed without merging